spring:
  data:
    mongodb:
      database: activitydb
      uri: ${MONGO_ACTIVITY_URI}
  kafka:
    bootstrap-servers: ${KAFKA_HOST}:9092
    consumer:
      group-id: activity-processor-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.FitnessService.AIService.models.Activity
        spring.json.trusted.packages: "*"

gemini:
  api:
    url: ${GEMINI_URL}
    key: ${GEMINI_KEY}

kafka:
  topic:
    name: activity-events

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST}:8761/eureka

server:
  port: 8083
