spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${KEYCLOAK_HOST}/realms/Fitness-App

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: userservice-production-7b33.up.railway.app
          predicates:
            - Path=/api/users/**
            - Path=/api/users

        - id: activity-service
          uri: activityservice-production-1daa.up.railway.app
          predicates:
            - Path=/api/activities/**
            - Path=/api/activities

        - id: ai-service
          uri: aiservice-production-51c1.up.railway.app
          predicates:
            - Path=/api/recommendations/**
            - Path=/api/recommendations

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST}:8761/eureka